using System;
using System.Collections.Generic;
using System.Text;

namespace BrickBreaker.Models.HitboxShapes.Polygon
{
    /// <summary>
    /// A vertex of a polygon object. Vertexes are "owned" by a polygon, but they can also exist on their own
    /// </summary>
    /// <seealso cref="BrickBreaker.Models.ICartesianable" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for Vertex
    public class Vertex : ICartesianable
    {
        Polygon Owner = null;
        double XPosOffset;
        double YPosOffset;

        public double XPos
        {
            get
            {
                if(this.Owner == null)
                {
                    return this.XPosOffset;
                }
                return this.Owner.XPos + this.XPosOffset;
            }
            set => throw new NotImplementedException();
        }
        public double YPos { get
            {
                if (this.Owner == null)
                {
                    return this.YPosOffset;
                }
                return this.Owner.YPos + this.YPosOffset; } set => throw new NotImplementedException(); }

        public Vertex(double xPosOffset, double yPosOffset, Polygon owner)
        {
            this.Owner = owner;
            this.XPosOffset = xPosOffset;
            this.YPosOffset = yPosOffset;
        }

        public Vertex(double xPosOffset, double yPosOffset)
        {
            this.Owner = null;
            this.XPosOffset = xPosOffset;
            this.YPosOffset = yPosOffset;
        }

    }
}
